name: places
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dependencies:
  flutter_svg: 0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/
    - assets/icons/Heart.svg
    - assets/icons/HeartFull.svg
    - assets/icons/Settings.svg
    - assets/icons/SettingsFull.svg
    - assets/icons/Map.svg
    - assets/icons/MapFull.svg
    - assets/icons/List.svg
    - assets/icons/ListFull.svg
    - assets/icons/Calendar.svg
    - assets/icons/Remove.svg
    - assets/icons/Share.svg
    - assets/icons/GO.svg
    - assets/icons/GOBig.svg
    - assets/icons/EmptyFavoritesPlaces.svg









  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Black.ttf
        - asset: res/fonts/Roboto-BlackItalic.ttf
        - asset: res/fonts/Roboto-Bold.ttf
        - asset: res/fonts/Roboto-BoldItalic.ttf
        - asset: res/fonts/Roboto-Italic.ttf
        - asset: res/fonts/Roboto-Light.ttf
        - asset: res/fonts/Roboto-LightItalic.ttf
        - asset: res/fonts/Roboto-Medium.ttf
        - asset: res/fonts/Roboto-MediumItalic.ttf
        - asset: res/fonts/Roboto-Regular.ttf
        - asset: res/fonts/Roboto-Thin.ttf
        - asset: res/fonts/Roboto-ThinItalic.ttf

